name: publish-documentation
description: Build and publish Wiki-based documentation using mkdocs
runs:
  using: composite
  steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
        gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
        path: base
        token: ${{ inputs.token }}
    - name: Checkout wiki
      uses: actions/checkout@v4
      with:
        path: wiki/docs
        repository: "${{ github.repository }}.wiki"
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: pip install mkdocs-material mdx_truly_sane_lists
      shell: bash
    - run: ls -alR
      shell: bash
    - name: Prepare pages build
      run: git checkout -b gh-pages
      working-directory: base
    - name: Build documentation
      run: mkdocs build --config-file mkdocs.yml
      working-directory: base
      shell: bash
    - name: Commit pages build
      run: git add . && git commit -a -m "Wiki update" && git push -f
      shell: bash
      working-directory: base
    - run: pwd && ls -alR && cd base && git remote -v
      shell: bash
      if: failure()
inputs:
  token:
    description: 'GitHub token'
    required: true
