name: publish-documentation
description: Build and publish Wiki-based documentation using mkdocs
runs:
  using: composite
  steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        path: base
        token: ${{ inputs.token }}
    - name: Checkout wiki
      uses: actions/checkout@v4
      with:
        path: wiki/docs
        repository: "${{ github.repository }}.wiki"
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: pip install mkdocs-material mdx_truly_sane_lists
      shell: bash
    - run: ls -alR
      shell: bash
    - name: Build documentation
      run: mkdocs gh-deploy --force --no-history --config-file mkdocs.yml
      working-directory: base
      shell: bash
    - run: pwd && ls -alR && cd base && git remote -v
      shell: bash
      if: failure()
inputs:
  token:
    description: 'GitHub token'
    required: true
